name: sums
description: "Sistema de Captura Operativa SUMS"
publish_to: 'none'

# 🚀 El cambio vital: subimos de +1 a +2 para que Google Play lo acepte
version: 1.0.0+2

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # --- UI & State Management ---
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  sqflite: ^2.3.0

  # --- Networking & Background ---
  http: ^1.6.0
  connectivity_plus: ^7.1.1
  workmanager: ^0.9.0+3
  shared_preferences: ^2.5.5

  # --- Database (Drift / SQLite) & Paths ---
  drift: ^2.34.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6
  path: ^1.9.1
  flutter_secure_storage: ^10.3.1
  flutter_jailbreak_detection: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- Code Generation ---
  build_runner: ^2.15.0
  drift_dev: ^2.34.1+1

  # --- Asset Tools ---
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "ic_launcher_imss"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/IMSS_SOLO_LOGO_PADDED.png"
  ios: true
  image_path: "assets/images/IMSS_SOLO_LOGO_PADDED.png"
  web:
    generate: true
    image_path: "assets/images/IMSS_SOLO_LOGO.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/IMSS_SOLO_LOGO.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/IMSS_SOLO_LOGO.png"